# -*- coding: utf-8 -*-

from . import res_partner
from . import product
from . import sale_order
from . import mrp_production
from . import mrp_bom
from . import stock_rule
from . import mrp_workorder
from . import mrp_workcenter
from . import stock_picking
from . import account_move_line
from . import custom_product_warehouse
from . import purchase
from . import payment_method
from . import payment_stripe
from . import custom_label_template
from . import shopify_instance
from . import shopify_res_partner_ept
from . import payment_transaction
from . import sale_order_line
from . import stock_scrap
from . import sale_order_import
from . import stock_move
from . import stock_picking_batch
from . import product_tag
from . import shipstation_instance_ept
from . import custom_design_tif
from . import product_attribute
from . import website
from . import delivery_carrier
from . import stock_landed_cost
from . import custom_product_bom 
from . import account_bank_statement_line
from . import stock_location
from . import stock_quant
from . import payment_gateway