# -*- coding: utf-8 -*-
{
    "name": "Custom - Drop Stitch",
    "summary": (
        """
        Custom - Drop Stitch
        """
    ),
    "author": "theERPbot",
    "website": "https://www.theerpbot.com",
    "version": "17.0.1.7.30",
    "development_status": "Production/Stable",
    "license": "LGPL-3",
    "installable": True,
    "application": True,
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "data/data.xml",
        "data/ir_cron_view.xml",
        "data/email_template.xml",
        "wizard/choose_delivery_carrier_view.xml",
        "report/product_label_reports.xml",
        "report/product_label_templates.xml",
        "report/report_deliveryslip.xml",
        "report/report_invoice.xml",
        "report/gift_message_label_template.xml",
        "report/report_wave_delivery_slip.xml",
        "views/custom_security.xml",
        "views/res_partner_view.xml",
        "views/product_view.xml",
        "views/product_attribute_data.xml",
        "views/sale_order_view.xml",
        "views/mrp_production_view.xml",
        "views/mrp_bom_view.xml",
        "views/sale_portal_templates.xml",
        "views/mrp_workorder_view.xml",
        "views/mrp_workcenter_view.xml",
        "views/stock_picking_views.xml",
        "views/custom_product_warehouse_view.xml",
        "views/templates_web_product.xml",
        "views/purchase_order_view.xml",
        "views/payment_method_view.xml",
        "views/payment_form_template.xml",
        "templates/shop_product.xml",
        "views/custom_label_template_view.xml",
        "views/shopify_instance_view.xml",
        "views/account_move_view.xml",
        "views/stock_move_view.xml",
        "views/sale_order_import_view.xml",
        "report/ir_actions_report_templates.xml",
        "views/stock_picking_batch_views.xml",
        "wizard/message_wizard_view.xml",
        "views/product_tag_view.xml",
        "views/custom_design_tif_view.xml",
        "views/delivery_carrier.xml",
        "views/stock_landed_cost_view.xml",
        "templates/product.xml",
        "templates/website_checkout.xml", 
        "templates/payment_view.xml",
        "views/custom_product_bom.xml",
        "views/account_bank_statement_line.xml",
        "views/stock_location_view.xml",
        'views/stock_quant.xml',
    ],
    "assets": {
        "web.assets_frontend": [
            "/custom_dropstitch/static/src/js/variant_mixin.js",
            "/custom_dropstitch/static/src/js/website_sale.js",
            "/custom_dropstitch/static/src/scss/base_layout.scss",
            "/custom_dropstitch/static/src/js/payment.js",
            ('after','/website_sale/static/src/js/website_sale_delivery.js','/custom_dropstitch/static/src/js/website_sale_delivery.js'),
        ],
        "web.assets_backend": [
            "/custom_dropstitch/static/src/scss/base_layout.scss",
            "/custom_dropstitch/static/src/js/product_template_attribute_line/product_template_attribute_line.js",
            "/custom_dropstitch/static/src/js/product_template_attribute_line/product_template_attribute_line.xml",
            "/custom_dropstitch/static/src/js/product_configurator_dialog/product_configurator_dialog.js",
            "/custom_dropstitch/static/src/js/product_configurator_dialog/SaleOrderLineProductField.js",
            "/custom_dropstitch/static/src/js/list_renderer/list_renderer.js",
            "/custom_dropstitch/static/src/js/field/float_field.js", 
            "/custom_dropstitch/static/src/js/widget.js",
            "/custom_dropstitch/static/src/xml/widget.xml",
        ],
    },
    "images": [],
    "depends": [
        "mail",
        "base",
        "stock",
        "product",
        "sale",
        "mrp",
        "mrp_workorder",
        "website_sale",
        "base_automation",
        "shopify_ept",
        "payment",
        "stripe_fee_ext",
        "website_sale_stock",
        "sale_product_configurator",
        "account",
        "common_connector_library",
        "sale_stock",
        "sale_mrp",
        "delivery_stock_picking_batch",
        "quality_control_picking_batch",
        "shipstation_ept",
        "delivery_ups_rest",
        "delivery_fedex",
        "aspl_website_partial_payment_ee",
        "stock_picking_batch",
        "sale_margin",
    ],
}
